return {
  "neovim/nvim-lspconfig",
  ---@class PluginLspOpts
  opts = {
    ---@type lspconfig.options
    servers = {
      -- tsserver will be automatically installed with mason and loaded with lspconfig
      intelephense = {
        stubs = {
          "bcmath",
          "bz2",
          "Core",
          "curl",
          "date",
          "dom",
          "fileinfo",
          "filter",
          "gd",
          "gettext",
          "hash",
          "iconv",
          "imap",
          "intl",
          "json",
          "libxml",
          "mbstring",
          "mcrypt",
          "mysql",
          "mysqli",
          "password",
          "pcntl",
          "pcre",
          "PDO",
          "pdo_mysql",
          "Phar",
          "readline",
          "regex",
          "session",
          "SimpleXML",
          "sockets",
          "sodium",
          "standard",
          "superglobals",
          "tokenizer",
          "xml",
          "xdebug",
          "xmlreader",
          "xmlwriter",
          "yaml",
          "zip",
          "zlib",
          "wordpress-stubs",
          "woocommerce-stubs",
          "acf-pro-stubs",
          "wordpress-globals",
          "wp-cli-stubs",
          "genesis-stubs",
          "polylang-stubs",
        },
      },
    },
  },
}
